# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\externalInterface\patient\getPatient.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCasePatient(HttpRunner):

    config = (
        Config("testcase description").base_url("${ENV(baseUrl_caiHong)}").verify(False)
    )

    teststeps = [
        Step(
            RunRequest("/hsb/wxfw/patient/3/130633199001036815")
            .get("/patient/3/130633199001036815")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCasePatient().test_start()
