# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\externalInterface\basicInformation\getProviderList.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetproviderlist(HttpRunner):

    config = Config("获取医院医生信息").base_url("${ENV(baseUrl_dongHua)}").verify(False)

    teststeps = [
        Step(
            RunRequest("获取医院医生信息接口")
            .get("/provider/list")
            .validate()
            .assert_equal("body.responseCode", "0")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetproviderlist().test_start()
