# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\externalInterface\appointment\getSchedulePlanList.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetscheduleplanlist(HttpRunner):

    config = Config("获取科室号源排班").base_url("${ENV(baseUrl_dongHua)}").verify(False)

    teststeps = [
        Step(
            RunRequest("获取某天排班信息接口")
            .get("/schedulePlan/list/date/${getTomorrowDate()}")
            .validate()
            .assert_equal("body.responseCode", "0")
            .assert_not_equal("body.data[0].totalCount", "0")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetscheduleplanlist().test_start()
