# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\externalInterface\appointment\getSchedulePlanList.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetscheduleplanlist(HttpRunner):

    config = (
        Config("挂号需先调通基础信息接口，获取医院科室、医生、号源等信息")
        .base_url("${ENV(baseUrl_dongHua)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("获取医院科室信息接口")
            .get("/organizationUnit/list")
            .extract()
            .with_jmespath("body.data[1].parentId", "parentId")
            .validate()
            .assert_equal("body.responseCode", "0")
            .assert_equal("body.data[0].levelId", 4)
            .assert_equal("body.data[1].levelId", 5)
            .assert_equal("body.data[6].levelId", 6)
            .assert_equal("body.data[0].organizationUnitId", "$parentId")
        ),
        Step(
            RunRequest("获取医院医生信息接口")
            .get("/provider/list")
            .validate()
            .assert_equal("body.responseCode", "0")
        ),
        Step(
            RunRequest("获取某天排班信息接口")
            .get("/schedulePlan/list/date/${getTomorrowDate()}")
            .validate()
            .assert_equal("body.responseCode", "0")
            .assert_not_equal("body.data[0].totalCount", "0")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetscheduleplanlist().test_start()
